In this step, we need to ask ourselves. What is the real problem in our project to be solved? That question will guide us for the entire process of analyzing the data.
    1.How do annual members and casual use cyclistic bikes differently ?
    2.What do we need to do to convert casual riders into annual members? (Marketing promotion focusing)

First, I am going to import all the data that I need. However, there are total 12 files as 12 months data of the company. Therefore, I need to combine those dataframe to one dataframe before cleaning and analyzing.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from csv import reader

Import all sources from Jan 2021 to Dec 2021

In [3]:

dt1 = pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202101-divvy-tripdata.csv")
dt2= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202102-divvy-tripdata.csv")
dt3= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202103-divvy-tripdata.csv")
dt4= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202104-divvy-tripdata.csv")
dt5=pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202105-divvy-tripdata.csv")
dt6= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202106-divvy-tripdata.csv")
dt7= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202107-divvy-tripdata.csv")
dt8= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202108-divvy-tripdata.csv")
dt9= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202109-divvy-tripdata.csv")
dt10=pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202110-divvy-tripdata.csv")
dt11= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202111-divvy-tripdata.csv")
dt12= pd.read_csv(r"C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\Cleaned-Tripdata\202112-divvy-tripdata.csv")

In [4]:
dt1.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_lenght,day_of_week
0,E19E6F1B8D4C42ED,electric_bike,1/23/2021 16:14,1/23/2021 16:24,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0:10:25,7
1,DC88F20C2C55F27F,electric_bike,1/27/2021 18:43,1/27/2021 18:47,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0:04:04,4
2,EC45C94683FE3F27,electric_bike,1/21/2021 22:35,1/21/2021 22:37,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0:01:20,5
3,4FA453A75AE377DB,electric_bike,1/7/2021 13:31,1/7/2021 13:42,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0:11:42,5
4,BE5E8EB4E7263A0B,electric_bike,1/23/2021 2:24,1/23/2021 2:24,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0:00:43,7

In [5]:
dt1.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'ride_lenght', 'day_of_week'],
      dtype='object')

In [6]:
dt1.info

<bound method DataFrame.info of                 ride_id  rideable_type       started_at         ended_at  \
0      E19E6F1B8D4C42ED  electric_bike  1/23/2021 16:14  1/23/2021 16:24
1      DC88F20C2C55F27F  electric_bike  1/27/2021 18:43  1/27/2021 18:47
2      EC45C94683FE3F27  electric_bike  1/21/2021 22:35  1/21/2021 22:37
3      4FA453A75AE377DB  electric_bike   1/7/2021 13:31   1/7/2021 13:42
4      BE5E8EB4E7263A0B  electric_bike   1/23/2021 2:24   1/23/2021 2:24
...                 ...            ...              ...              ...
96829  B1A5336E1412D8BF   classic_bike  1/19/2021 19:03  1/19/2021 20:10
96830  57EA5CB7DCD75F90   classic_bike   1/5/2021 18:42   1/5/2021 19:33
96831  815B319A078CC984   classic_bike   1/7/2021 17:59   1/7/2021 19:34
96832  6DB04151565CEE63   classic_bike   1/6/2021 19:20   1/6/2021 20:41
96833  8008C9C998083A1A    docked_bike  1/17/2021 13:20  1/17/2021 14:17

                    start_station_name start_station_id  \
0           California Ave & Cortez St            17660
1           California Ave & Cortez St            17660
2           California Ave & Cortez St            17660
3           California Ave & Cortez St            17660
4           California Ave & Cortez St            17660
...                                ...              ...
96829        Lake Shore Dr & Monroe St            13300
96830        Lake Shore Dr & Monroe St            13300
96831  Lakefront Trail & Bryn Mawr Ave     KA1504000152
96832  Lakefront Trail & Bryn Mawr Ave     KA1504000152
96833        Lake Shore Dr & Monroe St            13300

                      end_station_name end_station_id  start_lat  start_lng  \
0                                  NaN            NaN  41.900341 -87.696743
1                                  NaN            NaN  41.900333 -87.696707
2                                  NaN            NaN  41.900313 -87.696643
3                                  NaN            NaN  41.900399 -87.696662
4                                  NaN            NaN  41.900326 -87.696697
...                                ...            ...        ...        ...
96829  Lakefront Trail & Bryn Mawr Ave   KA1504000152  41.880958 -87.616743
96830  Lakefront Trail & Bryn Mawr Ave   KA1504000152  41.880958 -87.616743
96831  Lakefront Trail & Bryn Mawr Ave   KA1504000152  41.984037 -87.652310
96832  Lakefront Trail & Bryn Mawr Ave   KA1504000152  41.984037 -87.652310
96833        Lake Shore Dr & Monroe St          13300  41.880958 -87.616743

         end_lat    end_lng member_casual ride_lenght  day_of_week
0      41.890000 -87.720000        member     0:10:25            7
1      41.900000 -87.690000        member     0:04:04            4
2      41.900000 -87.700000        member     0:01:20            5
3      41.920000 -87.690000        member     0:11:42            5
4      41.900000 -87.700000        casual     0:00:43            7
...          ...        ...           ...         ...          ...
96829  41.984037 -87.652310        member     1:06:46            3
96830  41.984037 -87.652310        member     0:51:06            3
96831  41.984037 -87.652310        member     1:34:16            5
96832  41.984037 -87.652310        member     1:21:26            4
96833  41.880958 -87.616743        casual     0:56:58            1

[96834 rows x 15 columns]>

Aggregate all sources from Jan 2021 to Dec 2021

In [7]:
trip_data = pd.concat([dt1 , dt2 ,dt3, dt4, dt5, dt6, dt7, dt8, dt8, dt10, dt11, dt12])

In [8]:
trip_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_lenght,day_of_week
0,E19E6F1B8D4C42ED,electric_bike,1/23/2021 16:14,1/23/2021 16:24,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.89,-87.72,member,0:10:25,7
1,DC88F20C2C55F27F,electric_bike,1/27/2021 18:43,1/27/2021 18:47,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.90,-87.69,member,0:04:04,4
2,EC45C94683FE3F27,electric_bike,1/21/2021 22:35,1/21/2021 22:37,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.90,-87.70,member,0:01:20,5
3,4FA453A75AE377DB,electric_bike,1/7/2021 13:31,1/7/2021 13:42,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.92,-87.69,member,0:11:42,5
4,BE5E8EB4E7263A0B,electric_bike,1/23/2021 2:24,1/23/2021 2:24,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.90,-87.70,casual,0:00:43,7

In [9]:
total_columns = len(trip_data.ride_id)
print(total_columns)

5643268

In [10]:
print(trip_data.describe())

          start_lat     start_lng       end_lat       end_lng   day_of_week
count  5.643268e+06  5.643268e+06  5.638386e+06  5.638386e+06  5.643268e+06
mean   4.190125e+01 -8.764585e+01  4.190152e+01 -8.764607e+01  4.210475e+00
std    4.581241e-02  2.845398e-02  4.591948e-02  2.864138e-02  2.121642e+00
min    4.164000e+01 -8.784000e+01  4.139000e+01 -8.897000e+01  1.000000e+00
25%    4.188178e+01 -8.766000e+01  4.188189e+01 -8.766000e+01  2.000000e+00
50%    4.189897e+01 -8.764170e+01  4.189993e+01 -8.764182e+01  4.000000e+00
75%    4.192914e+01 -8.762772e+01  4.192923e+01 -8.762773e+01  6.000000e+00
max    4.207000e+01 -8.752000e+01  4.215000e+01 -8.749000e+01  7.000000e+00

After we combined mutiple dataframe to a data frame, we begin the cleaning stage.
    1.Deleting unneeded colums.
    2.I already used excel to define the ride lenght and day of week using columns that those are neccesery data to analyze. Thus, I will move to next step to check for bad data.

In [11]:
columns = ['start_lat', 'start_lng' , 'end_lat', 'end_lng']
trip_data = trip_data.drop(columns, axis = 1)

In [12]:
trip_data.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_lenght,day_of_week
0,E19E6F1B8D4C42ED,electric_bike,1/23/2021 16:14,1/23/2021 16:24,California Ave & Cortez St,17660,NaN,NaN,member,0:10:25,7
1,DC88F20C2C55F27F,electric_bike,1/27/2021 18:43,1/27/2021 18:47,California Ave & Cortez St,17660,NaN,NaN,member,0:04:04,4
2,EC45C94683FE3F27,electric_bike,1/21/2021 22:35,1/21/2021 22:37,California Ave & Cortez St,17660,NaN,NaN,member,0:01:20,5
3,4FA453A75AE377DB,electric_bike,1/7/2021 13:31,1/7/2021 13:42,California Ave & Cortez St,17660,NaN,NaN,member,0:11:42,5
4,BE5E8EB4E7263A0B,electric_bike,1/23/2021 2:24,1/23/2021 2:24,California Ave & Cortez St,17660,NaN,NaN,casual,0:00:43,7

In [13]:
print(trip_data['ride_lenght'].isna().sum())
print(trip_data['day_of_week'].isna().sum())

0
0

How many duplicate transaction records are there?

In [14]:
trip_data['ride_id'].duplicated().sum()

804363

Drop the duplicated records

In [15]:
trip_data = trip_data.drop_duplicates()

trip_data.duplicated().sum()

0

How many missing values are there?

In [16]:
trip_data.isnull().sum().sum()

2475209

Drop any columns with missing values.

In [17]:
trip_data = trip_data.dropna()

trip_data.isnull().sum().sum()

0

In [18]:
trip_data

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_lenght,day_of_week
9,B9F73448DFBE0D45,classic_bike,1/24/2021 19:15,1/24/2021 19:22,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,member,0:07:13,1
10,457C7F4B5D3DA135,electric_bike,1/23/2021 12:57,1/23/2021 13:02,California Ave & Cortez St,17660,California Ave & North Ave,13258,member,0:04:32,7
11,57C750326F9FDABE,electric_bike,1/9/2021 15:28,1/9/2021 15:37,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,casual,0:09:47,7
12,4D518C65E338D070,electric_bike,1/9/2021 15:28,1/9/2021 15:37,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,casual,0:08:57,7
13,9D08A3AFF410474D,classic_bike,1/24/2021 15:56,1/24/2021 16:07,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,casual,0:10:09,1
...,...,...,...,...,...,...,...,...,...,...,...
247528,E06135F650553F21,electric_bike,12/7/2021 15:55,12/7/2021 16:00,Canal St & Madison St,13341,Desplaines St & Kinzie St,TA1306000003,casual,0:04:40,3
247532,8DF0DBB049906332,electric_bike,12/1/2021 16:50,12/1/2021 16:55,Canal St & Madison St,13341,Desplaines St & Kinzie St,TA1306000003,casual,0:04:26,4
247536,CF407BBC3B9FAD63,electric_bike,12/6/2021 19:37,12/6/2021 19:44,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,member,0:07:01,2
247537,60BB69EBF5440E92,electric_bike,12/2/2021 8:57,12/2/2021 9:05,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,member,0:08:17,5
247539,37AC57E34B2E7E97,classic_bike,12/13/2021 8:45,12/13/2021 8:49,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,member,0:03:37,2

Drop any row that we do not need to answer the primary question

In [19]:
trip_data = trip_data.drop('start_station_id', axis = 1)
trip_data = trip_data.drop('end_station_id', axis = 1)
trip_data

,ride_id,rideable_type,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_lenght,day_of_week
9,B9F73448DFBE0D45,classic_bike,1/24/2021 19:15,1/24/2021 19:22,California Ave & Cortez St,Wood St & Augusta Blvd,member,0:07:13,1
10,457C7F4B5D3DA135,electric_bike,1/23/2021 12:57,1/23/2021 13:02,California Ave & Cortez St,California Ave & North Ave,member,0:04:32,7
11,57C750326F9FDABE,electric_bike,1/9/2021 15:28,1/9/2021 15:37,California Ave & Cortez St,Wood St & Augusta Blvd,casual,0:09:47,7
12,4D518C65E338D070,electric_bike,1/9/2021 15:28,1/9/2021 15:37,California Ave & Cortez St,Wood St & Augusta Blvd,casual,0:08:57,7
13,9D08A3AFF410474D,classic_bike,1/24/2021 15:56,1/24/2021 16:07,California Ave & Cortez St,Wood St & Augusta Blvd,casual,0:10:09,1
...,...,...,...,...,...,...,...,...,...
247528,E06135F650553F21,electric_bike,12/7/2021 15:55,12/7/2021 16:00,Canal St & Madison St,Desplaines St & Kinzie St,casual,0:04:40,3
247532,8DF0DBB049906332,electric_bike,12/1/2021 16:50,12/1/2021 16:55,Canal St & Madison St,Desplaines St & Kinzie St,casual,0:04:26,4
247536,CF407BBC3B9FAD63,electric_bike,12/6/2021 19:37,12/6/2021 19:44,Canal St & Madison St,Kingsbury St & Kinzie St,member,0:07:01,2
247537,60BB69EBF5440E92,electric_bike,12/2/2021 8:57,12/2/2021 9:05,Canal St & Madison St,Dearborn St & Monroe St,member,0:08:17,5
247539,37AC57E34B2E7E97,classic_bike,12/13/2021 8:45,12/13/2021 8:49,Michigan Ave & Jackson Blvd,Dearborn St & Monroe St,member,0:03:37,2

In [24]:
trip_data.to_csv(r'C:\Users\Ben\Desktop\Data Analyst Projects\Cyclist - Marketing Project\trip_data.csv', index=False)